#!/bin/bash

install_nala() {
    if command -v apt &> /dev/null; then
        echo "Installing nala..."
        sudo apt update
        sudo apt install -y nala
        return $?
    else
        echo "APT not found. Cannot install nala."
        return 1
    fi
}

install_nala
